name: Build and Push Docker Image to Docker Hub with SHA Tagging

on:
  push:
    branches:
      - main # Trigger on pushes to the `main` branch
  pull_request:
    branches:
      - main # Trigger on pull requests to `main`

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up the Docker tag
    - name: Set Docker tag
      id: vars
      run: |
        SHORT_SHA=${{ github.sha::0:7 }} # Use the first 7 characters of the GitHub SHA
        echo "TAG=${SHORT_SHA}" >> $GITHUB_ENV
        echo "LATEST_TAG=latest" >> $GITHUB_ENV

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored in secrets
        password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password stored in secrets

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.TAG }} ci
        docker tag ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.TAG }} ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.LATEST_TAG }}

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.TAG }}
        docker push ${{ secrets.DOCKER_USERNAME }}/pos-sytem-usecase:${{ env.LATEST_TAG }}
